language: node_js
node_js:
  - '5'
  - '4'
addons:
  code_climate:
    repo_token: 270ec81063e88c1e508c9d7c13d07194093ef76701037f27d2fbbca3b04ea579
after_script:
  - npm run coverage
  - cat coverage/lcov.info | node_modules/.bin/codeclimate-test-reporter
