packages:
  - .

catalogMode: manual

engineStrict: true

hoist: false

ignoreDepScripts: true

minimumReleaseAge: 10800

minimumReleaseAgeExclude:
  - '@bbc/*'
  - '@ibl/*'

overrides:
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  micromatch@<4.0.8: '>=4.0.8'
  path-to-regexp@>=4.0.0 <6.3.0: '>=6.3.0'

publicHoistPattern:
  - eslint-*
  - '@eslint/*'
  - '@typescript-eslint/*'
  - jest

recursiveInstall: false

sharedWorkspaceLockfile: false
